apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeday-app-integ
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/anandf/code-to-deployment.git'
    path: kustomize_kubeday/overlays/integ
    targetRevision: HEAD
    kustomize:
      images:
        - >-
          KUBEDAY_IMAGE=http://quay.io/savitaashture/kubeday-app:main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubeday-integ
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
