apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeday-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anandf/code-to-deployment.git
    targetRevision: HEAD
    path: kubeday-app/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeday-prod
