apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeday-app-integ
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/KUBEDAY_IMAGE.update-strategy: digest
    argocd-image-updater.argoproj.io/image-list: KUBEDAY_IMAGE=quay.io/savitaashture/kubeday-app:main
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/anandf/code-to-deployment.git'
    path: kustomize_kubeday/overlays/integ
    targetRevision: HEAD
    kustomize:
      images:
        - >-
          KUBEDAY_IMAGE=http://quay.io/savitaashture/kubeday-app:main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubeday-integ
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
