apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeday-app
spec:
  replicas: 2
  template:
    spec:
    containers:
      - name: kubeday-app
        image: quay.io/savitaashture/kaniko-chains:main
        ports:
          - containerPort: 80
