apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeday-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kubeday-app
    spec:
      containers:
        - name: kubeday-app
          image: quay.io/savitaashture/kubeday-app:main
          ports:
            - containerPort: 80
