apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: replica-patch.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: image-patch.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
